#!/usr/bin/env python3
import getpass
from netmiko import ConnectHandler
from datetime import datetime

user = input("Enter your username: ")
password = getpass.getpass()

iosv_l2_sa1 = {
    'device_type': 'cisco_ios',
    'host': 'SWA01-L2',
    'ip': '10.255.1.4',
    'username': user,
    'password': password,
}

iosv_l2_sa2 = {
    'device_type': 'cisco_ios',
    'host': 'SWA02-L2',
    'ip': '10.255.1.5',
    'username': user,
    'password': password,
}

iosv_l2_sc1 = {
    'device_type': 'cisco_ios',
    'host': 'SWC00-L3',
    'ip': '10.255.1.3',
    'username': user,
    'password': password,
}

date = datetime.now().strftime('_%m_%d_%Y_%H_%M_')
all_devices = [iosv_l2_sa1, iosv_l2_sa2, iosv_l2_sc1]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    net_connect.send_command('terminal length 0')
    output = net_connect.send_command('show running-config')
    f = open(devices['host'] + date + ".txt", "a")
    print(output, file=f)
    f.close()
